name: build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Docker login
        if: github.ref_name == 'dev' || github.ref_name == 'main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image to main
        if: github.ref_name == 'main'
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/freegpt:latest

      - name: Docker image push to dev
        if: github.ref_name == 'dev'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/freegpt:dev

      - name: Docker image push main
        if: github.ref_name == 'main'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/freegpt:latest
