name: ubuntu-gcc13

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Docker login
        if: github.ref_name == 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKERHUB_TOKEN }}

      - name: Build the Docker image to main
        if: github.ref_name == 'main'
        run: |
          docker build . -t ${{ DOCKERHUB_USERNAME }}/freegpt:latest

      - name: Docker image push main
        if: github.ref_name == 'main'
        run: docker push ${{ DOCKERHUB_USERNAME }}/freegpt:latest
